version: "3.9"
services:
  # Webserver running PHP-FPM and nginx
  web:
    build:
      context: ./.docker/web
      dockerfile: Dockerfile
    container_name: web
    restart: unless-stopped
    working_dir: /var/www
    extra_hosts:
      - "sso.ukcp.devapp:127.0.0.1"
      - "ukcp.devapp:127.0.0.1"
    ports:
      - "80:80"
      - "443:443"
      - "6001:6001"
    volumes:
      - type: bind
        source: .
        target: /var/www/ukcp
      - ./.docker/web/sso:/var/www/sso
      - ./.docker/web/etc/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - ukcp-network

  # Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./.docker/mysql/etc/mysql/my.cnf:/etc/mysql/conf.d/config-file.cnf
    environment:
      MYSQL_DATABASE: uk_plugin
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    networks:
      - ukcp-network

  # Database for test suite
  mysql-test:
    image: mysql:8.0
    container_name: mysql-test
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3360:3360"
    volumes:
      - mysqltestdata:/var/lib/mysql
      - ./.docker/mysql/etc/mysql/my.cnf:/etc/mysql/conf.d/config-file.cnf
    environment:
      MYSQL_DATABASE: uk_plugin
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
      MYSQL_TCP_PORT: 3360
    networks:
      - ukcp-network

  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - ukcp-network

# Netwokring
networks:
  ukcp-network:
    driver: bridge

#Volumes
volumes:
  mysqldata:
    driver: local
  mysqltestdata:
    driver: local
