[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-yaml" },
  { id = "check-toml" },
  { id = "check-merge-conflict" },
  { id = "check-added-large-files" },
  { id = "detect-private-key" },
]

[[repos]]
repo = "local"
hooks = [
  { id = "pint", name = "Laravel Pint", entry = "vendor/bin/pint", language = "system", files = "\\.php$", exclude = "^tests/" },
]
