<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePluginErrorsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('plugin_error', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('user_id')->comment('The user who the report is attributed to');
            $table->boolean('user_report')->comment('Whether the report was generated by the user or the plugin');
            $table->json('data')->comment('Report data');
            $table->timestamps();

            $table->foreign('user_id')
                ->references('id')->on('user');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('plugin_error');
    }
}
