<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class AddDepartureIntervalGroupPairs extends Migration
{
    /**
     * Pair format:
     *
     * 0 - First group name
     * 1 - Second group name
     * 2 - Interval in seconds when going First group -> second group
     */
    const PAIRS = [
        [
            'EGBB_SID',
            'EGBB_SID',
            120
        ],
        [
            'EGCC_EKLAD_KUXEM_23',
            'EGCC_EKLAD_KUXEM_23',
            120,
        ],
        [
            'EGCC_EKLAD_KUXEM_23',
            'EGCC_LISTO_23',
            60,
        ],
        [
            'EGCC_EKLAD_KUXEM_23',
            'EGCC_MONTY_23',
            120,
        ],
        [
            'EGCC_EKLAD_KUXEM_23',
            'EGCC_SANBA_23',
            120,
        ],
        [
            'EGCC_EKLAD_KUXEM_23',
            'EGCC_NORTH_EAST_23',
            120,
        ],
        [
            'EGCC_LISTO_23',
            'EGCC_LISTO_23',
            120,
        ],
        [
            'EGCC_LISTO_23',
            'EGCC_EKLAD_KUXEM_23',
            60,
        ],
        [
            'EGCC_LISTO_23',
            'EGCC_MONTY_23',
            60,
        ],
        [
            'EGCC_LISTO_23',
            'EGCC_NORTH_EAST_23',
            120,
        ],
        [
            'EGCC_MONTY_23',
            'EGCC_EKLAD_KUXEM_23',
            120,
        ],
        [
            'EGCC_MONTY_23',
            'EGCC_LISTO_23',
            60,
        ],
        [
            'EGCC_MONTY_23',
            'EGCC_MONTY_23',
            120,
        ],
        [
            'EGCC_MONTY_23',
            'EGCC_NORTH_EAST_23',
            120,
        ],
        [
            'EGCC_MONTY_23',
            'EGCC_SANBA_23',
            120,
        ],
        [
            'EGCC_NORTH_EAST_23',
            'EGCC_EKLAD_KUXEM_23',
            60,
        ],
        [
            'EGCC_NORTH_EAST_23',
            'EGCC_LISTO_23',
            60,
        ],
        [
            'EGCC_NORTH_EAST_23',
            'EGCC_MONTY_23',
            60,
        ],
        [
            'EGCC_NORTH_EAST_23',
            'EGCC_NORTH_EAST_23',
            120,
        ],
        [
            'EGCC_NORTH_EAST_23',
            'EGCC_SANBA_23',
            60,
        ],
        [
            'EGCC_SANBA_23',
            'EGCC_EKLAD_KUXEM_23',
            120,
        ],
        [
            'EGCC_SANBA_23',
            'EGCC_MONTY_23',
            60,
        ],
        [
            'EGCC_SANBA_23',
            'EGCC_NORTH_EAST_23',
            60,
        ],
        [
            'EGCC_SANBA_23',
            'EGCC_SANBA_23',
            120,
        ],
        [
            'EGCC_ASMIM_05',
            'EGCC_ASMIM_05',
            120,
        ],
        [
            'EGCC_ASMIM_05',
            'EGCC_DESIG_05',
            60,
        ],
        [
            'EGCC_ASMIM_05',
            'EGCC_POL_05',
            60,
        ],
        [
            'EGCC_ASMIM_05',
            'EGCC_LISTO_05',
            60,
        ],
        [
            'EGCC_ASMIM_05',
            'EGCC_MONTY_05',
            120,
        ],
        [
            'EGCC_DESIG_05',
            'EGCC_ASMIM_05',
            60,
        ],
        [
            'EGCC_DESIG_05',
            'EGCC_DESIG_05',
            120,
        ],
        [
            'EGCC_DESIG_05',
            'EGCC_LISTO_05',
            60,
        ],
        [
            'EGCC_DESIG_05',
            'EGCC_MONTY_05',
            120,
        ],
        [
            'EGCC_DESIG_05',
            'EGCC_POL_05',
            120,
        ],
        [
            'EGCC_LISTO_05',
            'EGCC_ASMIM_05',
            60,
        ],
        [
            'EGCC_LISTO_05',
            'EGCC_DESIG_05',
            60,
        ],
        [
            'EGCC_LISTO_05',
            'EGCC_LISTO_05',
            120,
        ],
        [
            'EGCC_LISTO_05',
            'EGCC_MONTY_05',
            60,
        ],
        [
            'EGCC_LISTO_05',
            'EGCC_POL_05',
            60,
        ],
        [
            'EGCC_MONTY_05',
            'EGCC_ASMIM_05',
            120,
        ],
        [
            'EGCC_MONTY_05',
            'EGCC_DESIG_05',
            60,
        ],
        [
            'EGCC_MONTY_05',
            'EGCC_LISTO_05',
            60,
        ],
        [
            'EGCC_MONTY_05',
            'EGCC_MONTY_05',
            120,
        ],
        [
            'EGCC_MONTY_05',
            'EGCC_POL_05',
            60,
        ],
        [
            'EGCC_POL_05',
            'EGCC_ASMIM_05',
            60,
        ],
        [
            'EGCC_POL_05',
            'EGCC_DESIG_05',
            120,
        ],
        [
            'EGCC_POL_05',
            'EGCC_LISTO_05',
            60,
        ],
        [
            'EGCC_POL_05',
            'EGCC_MONTY_05',
            60,
        ],
        [
            'EGCC_POL_05',
            'EGCC_POL_05',
            60,
        ],
        [
            'EGCN_ROGAG_02',
            'EGCN_ROGAG_02',
            120,
        ],
        [
            'EGCN_UPTON_02',
            'EGCN_UPTON_02',
            180,
        ],
        [
            'EGCN_ROGAG_02',
            'EGCN_UPTON_02',
            60,
        ],
        [
            'EGCN_UPTON_02',
            'EGCN_ROGAG_02',
            60,
        ],
        [
            'EGCN_UPTON_20',
            'EGCN_UPTON_20',
            180,
        ],
        [
            'EGCN_UPTON_20',
            'EGCN_ROGAG_20',
            120,
        ],
        [
            'EGCN_ROGAG_20',
            'EGCN_ROGAG_20',
            120,
        ],
        [
            'EGCN_ROGAG_20',
            'EGCN_UPTON_20',
            120,
        ],
        [
            'EGFF_SID',
            'EGFF_SID',
            120,
        ],
        [
            'EGGD_SID',
            'EGGD_SID',
            120,
        ],
        [
            'EGGW_CPT_26',
            'EGGW_CPT_26',
            120,
        ],
        [
            'EGGW_CPT_26',
            'EGGW_DET_MATCH_26',
            60,
        ],
        [
            'EGGW_CPT_26',
            'EGGW_OLNEY_26',
            120,
        ],
        [
            'EGGW_DET_MATCH_26',
            'EGGW_CPT_26',
            120,
        ],
        [
            'EGGW_DET_MATCH_26',
            'EGGW_DET_MATCH_26',
            120,
        ],
        [
            'EGGW_DET_MATCH_26',
            'EGGW_OLNEY_26',
            120,
        ],
        [
            'EGGW_OLNEY_26',
            'EGGW_CPT_26',
            120,
        ],
        [
            'EGGW_OLNEY_26',
            'EGGW_DET_MATCH_26',
            60,
        ],
        [
            'EGGW_OLNEY_26',
            'EGGW_OLNEY_26',
            120,
        ],
        [
            'EGGW_CPT_08',
            'EGGW_CPT_08',
            240,
        ],
        [
            'EGGW_CPT_08',
            'EGGW_DET_MATCH_08',
            240,
        ],
        [
            'EGGW_CPT_08',
            'EGGW_OLNEY_08',
            240,
        ],
        [
            'EGGW_DET_MATCH_08',
            'EGGW_CPT_08',
            60,
        ],
        [
            'EGGW_DET_MATCH_08',
            'EGGW_DET_MATCH_08',
            120,
        ],
        [
            'EGGW_DET_MATCH_08',
            'EGGW_OLNEY_08',
            120,
        ],
        [
            'EGGW_OLNEY_08',
            'EGGW_CPT_08',
            60,
        ],
        [
            'EGGW_OLNEY_08',
            'EGGW_DET_MATCH_08',
            60,
        ],
        [
            'EGGW_OLNEY_08',
            'EGGW_OLNEY_08',
            120,
        ],
        [
            'EGJB_SID',
            'EGJB_SID',
            120,
        ],
        [
            'EGJJ_SID',
            'EGJJ_SID',
            120,
        ],
    ];

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $groups = DB::table('sid_departure_interval_groups')->get()->mapWithKeys(
            function ($group) {
                return [$group->key => $group->id];
            }
        );

        foreach (self::PAIRS as $pair) {
            DB::table('sid_departure_interval_group_sid_departure_interval_group')
                ->insert(
                    [
                        'lead_group_id' =>  $groups[$pair[0]],
                        'follow_group_id' =>  $groups[$pair[1]],
                        'interval' =>  $pair[2],
                    ]
                );
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        DB::table('sid_departure_interval_group_sid_departure_interval_group')->delete();
    }
}
