<?php

use App\Models\Airfield\Airfield;
use App\Models\Airfield\VisualReferencePoint;
use App\Services\SectorfileService;
use Illuminate\Database\Migrations\Migration;

class AddVrpData extends Migration
{
    const VRPS = [
        [
            'name' => 'A1(M) JUNCTION 4',
            'short_name' => 'A1 J4',
            'coordinate' => '514645N 0001328W',
            'airfields' => ['EGGW'],
        ],
        [
            'name' => 'A1/A57 CLUMBER INTERCHANGE',
            'short_name' => 'Clumb',
            'coordinate' => '531747N 0010156W',
            'airfields' => ['EGCN', 'EGNE'],
        ],
        [
            'name' => 'A1/M18 WADWORTH INTERCHANGE',
            'short_name' => 'Wadworth',
            'coordinate' => '532845N 0010854W',
            'airfields' => ['EGCN'],
        ],
        [
            'name' => 'AINTREE RACECOURSE',
            'short_name' => 'Aintree',
            'coordinate' => '532836.00N 0025635.00W',
            'airfields' => ['EGGP'],
        ],
        ['name' => 'ALDERBURY', 'short_name' => 'Alder', 'coordinate' => '510255N 0014350W', 'airfields' => ['EGLS'],],
        [
            'name' => 'ALDERLEY EDGE HILL',
            'short_name' => 'Alderley',
            'coordinate' => '531743.00N 0021244.00W',
            'airfields' => ['EGCC'],
        ],
        [
            'name' => 'ALDERNEY LIGHTHOUSE',
            'short_name' => 'ALDERNEY',
            'coordinate' => '494344.83N 0020951.24W',
            'airfields' => ['EGJJ', 'EGJB'],
        ],
        [
            'name' => 'ALEXANDRIA',
            'short_name' => 'Alexa',
            'coordinate' => '555920.00N 0043435.00W',
            'airfields' => ['EGPF'],
        ],
        [
            'name' => 'ALLY PALLY',
            'short_name' => 'ALLY',
            'coordinate' => '513539.79N 0000746.90W',
            'airfields' => ['EGLC', 'EGLL'],
        ],
        ['name' => 'ALSTON', 'short_name' => 'Alston', 'coordinate' => '544834N 0022638W', 'airfields' => ['EGNC'],],
        ['name' => 'ALTON', 'short_name' => 'Alton', 'coordinate' => '510907N 0005758W', 'airfields' => ['EGLF'],],
        ['name' => 'ANNAN', 'short_name' => 'Annan', 'coordinate' => '545923N 0031521W', 'airfields' => ['EGNC'],],
        [
            'name' => 'ARDMORE POINT',
            'short_name' => 'Ard',
            'coordinate' => '555817.00N 0044157.00W',
            'airfields' => ['EGPF'],
        ],
        [
            'name' => 'ARSENAL',
            'short_name' => 'Ars',
            'coordinate' => '513317.94N 0000630.56W',
            'airfields' => ['EGLC'],
        ],
        [
            'name' => 'ARTHURS SEAT',
            'short_name' => 'Arth',
            'coordinate' => '555638.00N 0030942.00W',
            'airfields' => ['EGPH'],
        ],
        [
            'name' => 'ASCOT',
            'short_name' => 'Ascot',
            'coordinate' => '512514.57N 0003933.07W',
            'airfields' => ['EGLL'],
        ],
        [
            'name' => 'ATTLEBRIDGE',
            'short_name' => 'Attle',
            'coordinate' => '524136N 0010631E',
            'airfields' => ['EGSH'],
        ],
        [
            'name' => 'AUDLEY END RAILWAY STATION',
            'short_name' => 'Audley',
            'coordinate' => '520015N 0001225E',
            'airfields' => ['EGSS'],
        ],
        ['name' => 'AXMINSTER', 'short_name' => 'Axmin', 'coordinate' => '504654N 0025954W', 'airfields' => ['EGTE'],],
        ['name' => 'AYLSHAM', 'short_name' => 'Ayls', 'coordinate' => '524704N 0011519E', 'airfields' => ['EGSH'],],
        [
            'name' => 'BAGSHOT',
            'short_name' => 'Bags',
            'coordinate' => '512057N 0004157W',
            'airfields' => ['EGLF', 'EGLL'],
        ],
        [
            'name' => 'BAILLIESTON',
            'short_name' => 'Bail',
            'coordinate' => '555110.00N 0040522.00W',
            'airfields' => ['EGPF'],
        ],
        [
            'name' => 'BALLYMENA',
            'short_name' => 'Bally',
            'coordinate' => '545148.00N 0061624.00W',
            'airfields' => ['EGAA'],
        ],
        [
            'name' => 'BAMPTON',
            'short_name' => 'Bampt',
            'coordinate' => '514330.00N 0013248.00W',
            'airfields' => ['EGVN'],
        ],
        [
            'name' => 'BANBURY RESERVOIR',
            'short_name' => 'Banb',
            'coordinate' => '513616N 0000206W',
            'airfields' => ['EGLC'],
        ],
        [
            'name' => 'BANCHORY',
            'short_name' => 'Banch',
            'coordinate' => '570300.00N 0023006.00W',
            'airfields' => ['EGPD'],
        ],
        [
            'name' => 'BARRHEAD',
            'short_name' => 'Barr',
            'coordinate' => '554800.00N 0042330.00W',
            'airfields' => ['EGPF'],
        ],
        [
            'name' => 'BARROW TANKS RESERVOIRS',
            'short_name' => 'Barrow',
            'coordinate' => '512423.04N 0023945.86W',
            'airfields' => ['EGGD'],
        ],
        [
            'name' => 'BATH RACECOURSE',
            'short_name' => 'Bath',
            'coordinate' => '512501.44N 0022414.51W',
            'airfields' => ['EGGD'],
        ],
        [
            'name' => 'BATHGATE',
            'short_name' => 'Bath',
            'coordinate' => '555410.00N 0033825.00W',
            'airfields' => ['EGPH'],
        ],
        [
            'name' => 'BEAULIEU DISUSED AD',
            'short_name' => 'Beau',
            'coordinate' => '504815N 0013014W',
            'airfields' => ['EGHI', 'EGHH',],
        ],
        [
            'name' => 'BECKTON ROUNDABOUT',
            'short_name' => 'Beck',
            'coordinate' => '513131N 0000424E',
            'airfields' => ['EGLC'],
        ],
        [
            'name' => 'BEESTON CASTLE',
            'short_name' => 'Bees',
            'coordinate' => '530742N 0024131W',
            'airfields' => ['EGNR'],
        ],
        [
            'name' => 'BELAIR PARK',
            'short_name' => 'Belair',
            'coordinate' => '512635.83N 0000522.34W',
            'airfields' => ['EGLC'],
        ],
        [
            'name' => 'BERNERS LAKE',
            'short_name' => 'Bern',
            'coordinate' => '514549.40N 0001810.79E',
            'airfields' => ['EGSS'],
        ],
        ['name' => 'BILLERICAY', 'short_name' => 'Bill', 'coordinate' => '513800N 0002500E', 'airfields' => ['EGMC'],],
        [
            'name' => 'BILLINGSHURST',
            'short_name' => 'Bill',
            'coordinate' => '510054.00N 0002700.00W',
            'airfields' => ['EGKK'],
        ],
        [
            'name' => 'BISHOP WOOD',
            'short_name' => 'Bish',
            'coordinate' => '534833.26N 0010931.17W',
            'airfields' => ['EGCM'],
        ],
        [
            'name' => 'BISHOPS WALTHAM',
            'short_name' => 'Bish',
            'coordinate' => '505717.00N 0011235.00W',
            'airfields' => ['EGHI'],
        ],
        [
            'name' => 'BISHOPTON',
            'short_name' => 'Bish',
            'coordinate' => '555408.00N 0043006.00W',
            'airfields' => ['EGPF'],
        ],
        [
            'name' => 'BITTESWELL INDUSTRIAL ESTATE',
            'short_name' => 'Bittes',
            'coordinate' => '522728N 0011447W',
            'airfields' => ['EGBE'],
        ],
        [
            'name' => 'BLAGDON LAKE',
            'short_name' => 'Blag',
            'coordinate' => '512014N 0024247W',
            'airfields' => ['EGGD'],
        ],
        [
            'name' => 'BLAYDON',
            'short_name' => 'Blay',
            'coordinate' => '545806.00N 0014137.00W',
            'airfields' => ['EGNT'],
        ],
        [
            'name' => 'BLYTH WINDFARM',
            'short_name' => 'Blyth',
            'coordinate' => '550724N 0012937W',
            'airfields' => ['EGNT'],
        ],
        ['name' => 'BODAM', 'short_name' => 'Bodam', 'coordinate' => '595506N 0011606W', 'airfields' => ['EGPB'],],
        [
            'name' => 'BOLAM LAKE',
            'short_name' => 'Bolam',
            'coordinate' => '550753.00N 0015228.00W',
            'airfields' => ['EGNT'],
        ],
        [
            'name' => 'BORRAS QUARRY',
            'short_name' => 'Borras',
            'coordinate' => '530405.57N 0025705.71W',
            'airfields' => ['EGNR'],
        ],
        [
            'name' => 'BOTTESFORD DISUSED',
            'short_name' => 'Bottes',
            'coordinate' => '525753.00N 0004654.00W',
            'airfields' => ['EGNX'],
        ],
        ['name' => 'BRAE', 'short_name' => 'Brae', 'coordinate' => '602349N 0012114W', 'airfields' => ['EGPM'],],
        [
            'name' => 'BRAINTREE',
            'short_name' => 'Brain',
            'coordinate' => '515242.00N 0003314.00E',
            'airfields' => ['EGSS'],
        ],
        [
            'name' => 'BRENT RESERVOIR',
            'short_name' => 'Brent',
            'coordinate' => '513401.07N 0001521.93W',
            'airfields' => ['EGLC', 'EGLL'],
        ],
        ['name' => 'BRIGG', 'short_name' => 'Brigg', 'coordinate' => '533312N 0002912W', 'airfields' => ['EGNJ'],],
        [
            'name' => 'BRIGHTON MARINA',
            'short_name' => 'Bri Mar',
            'coordinate' => '504839N 0000603W',
            'airfields' => ['EGKA'],
        ],
        [
            'name' => 'BROUGHTY CASTLE',
            'short_name' => 'Broughty',
            'coordinate' => '562745N 0025211W',
            'airfields' => ['EGPN'],
        ],
        ['name' => 'BRUNDALL', 'short_name' => 'Brund', 'coordinate' => '523704N 0012600E', 'airfields' => ['EGSH'],],
        ['name' => 'BUCKLAND', 'short_name' => 'Buck', 'coordinate' => '511424N 0001445W', 'airfields' => ['EGKR'],],
        [
            'name' => 'BULLINGTON CROSS',
            'short_name' => 'Bulli',
            'coordinate' => '511030.61N 0012021.49W',
            'airfields' => ['EGHI'],
        ],
        ['name' => 'BUNCRANA', 'short_name' => 'Bunc', 'coordinate' => '550800N 0072724W', 'airfields' => ['EGAE'],],
        [
            'name' => 'BURFORD',
            'short_name' => 'Bur',
            'coordinate' => '514824.00N 0013812.00W',
            'airfields' => ['EGVN'],
        ],
        [
            'name' => 'BURGESS PARK',
            'short_name' => 'Burg',
            'coordinate' => '512905.58N 0000446.37W',
            'airfields' => ['EGLC'],
        ],
        [
            'name' => 'BURLTON GATE',
            'short_name' => 'Burl',
            'coordinate' => '525000.49N 0024817.86W',
            'airfields' => ['SLEAP'],
        ],
        [
            'name' => 'BURNHAM',
            'short_name' => 'Burn',
            'coordinate' => '513108.45N 0004037.87W',
            'airfields' => ['EGLL'],
        ],
        [
            'name' => 'BURTONWOOD',
            'short_name' => 'Burt',
            'coordinate' => '532500.00N 0023817.00W',
            'airfields' => ['EGGP', 'EGCC'],
        ],
        [
            'name' => 'BUTSER HILL MAST',
            'short_name' => 'Bust',
            'coordinate' => '505836N 0005856W',
            'airfields' => ['EGHI'],
        ],
        [
            'name' => 'BUXTON',
            'short_name' => 'Buxt',
            'coordinate' => '531521.00N 0015446.00W',
            'airfields' => ['EGCC'],
        ],
        [
            'name' => 'BYFLEET BRIDGE',
            'short_name' => 'Byfl',
            'coordinate' => '512023.47N 0002906.69W',
            'airfields' => ['EGLL'],
        ],
        ['name' => 'CAISTOR', 'short_name' => 'Caist', 'coordinate' => '532946N 0001906W', 'airfields' => ['EGNJ'],],
        [
            'name' => 'CALSHOT',
            'short_name' => 'Cals',
            'coordinate' => '504904.00N 0011945.00W',
            'airfields' => ['EGHI'],
        ],
        ['name' => 'CANAL BEND', 'short_name' => 'Canal', 'coordinate' => '513902N 0002537W', 'airfields' => ['EGTR'],],
        [
            'name' => 'CANFIELD A120/B1256 INT',
            'short_name' => 'Can',
            'coordinate' => '515213.72N 0001923.17E',
            'airfields' => ['EGSS'],
        ],
        [
            'name' => 'CAP DE LA HAGUE',
            'short_name' => 'Cap DLH',
            'coordinate' => '494300N 0015600W',
            'airfields' => ['EGJJ', 'EGJB'],
        ],
        [
            'name' => 'CARDIFF DOCKS',
            'short_name' => 'Docks',
            'coordinate' => '512724.00N 0030906.00W',
            'airfields' => ['EGFF', 'EGSY'],
        ],
        ['name' => 'CARROWKEEL', 'short_name' => 'Carro', 'coordinate' => '550730N 0071142W', 'airfields' => ['EGAE'],],
        [
            'name' => 'CARTERET LIGHTHOUSE',
            'short_name' => 'Carter',
            'coordinate' => '492224.00N 0014824.00W',
            'airfields' => ['EGJJ', 'EGJB'],
        ],
        [
            'name' => 'CASTLETOWN AERODROME (DISUSED)',
            'short_name' => 'Castle',
            'coordinate' => '583507N 0032101W',
            'airfields' => ['EGPC'],
        ],
        [
            'name' => 'CHARLBURY',
            'short_name' => 'Charl',
            'coordinate' => '515218.00N 0012854.00W',
            'airfields' => ['EGVN'],
        ],
        [
            'name' => 'CHEDDAR RESERVOIR',
            'short_name' => 'Chedd',
            'coordinate' => '511647.00N 0024805.00W',
            'airfields' => ['EGGD'],
        ],
        [
            'name' => 'CHELMSFORD',
            'short_name' => 'Chelm',
            'coordinate' => '514400.00N 0002824.00E',
            'airfields' => ['EGSS'],
        ],
        [
            'name' => 'CHESTER (A55(T)/A51(T))',
            'short_name' => 'Chest',
            'coordinate' => '531142N 0025038W',
            'airfields' => ['EGGP', 'EGNR'],
        ],
        [
            'name' => 'CHEW VALLEY',
            'short_name' => 'Chew',
            'coordinate' => '511930.00N 0023542.00W',
            'airfields' => ['EGGD'],
        ],
        [
            'name' => 'CHIPPENHAM',
            'short_name' => 'Chip',
            'coordinate' => '512736.00N 0020724.00W',
            'airfields' => ['EGGD'],
        ],
        [
            'name' => 'CHIPPING ONGAR A414/B184 INT',
            'short_name' => 'Chip',
            'coordinate' => '514245.56N 0001442.02E',
            'airfields' => ['EGSS'],
        ],
        [
            'name' => 'CHURCH BROUGHTON DISUSED',
            'short_name' => 'Ch. Br.',
            'coordinate' => '525310.00N 0014154.00W',
            'airfields' => ['EGNX'],
        ],
        [
            'name' => 'CHURCHILL',
            'short_name' => 'Church',
            'coordinate' => '512000.00N 0024736.00W',
            'airfields' => ['EGGD'],
        ],
        [
            'name' => 'CLATWORTHY RESERVOIR',
            'short_name' => 'Clat',
            'coordinate' => '510422.78N 0032209.18W',
            'airfields' => ['EGFF', 'EGSY'],
        ],
        ['name' => 'CLAUDY', 'short_name' => 'Claudy', 'coordinate' => '545442N 0070912W', 'airfields' => ['EGAE'],],
        [
            'name' => 'CLEVEDON',
            'short_name' => 'Cleve',
            'coordinate' => '512621.00N 0025105.00W',
            'airfields' => ['EGGD'],
        ],
        [
            'name' => 'CLIFTON SUSPENSION BRIDGE',
            'short_name' => 'Clft S.',
            'coordinate' => '512718.00N 0023740.00W',
            'airfields' => ['EGGD'],
        ],
        [
            'name' => 'CLUNTOE (DISUSED AD)',
            'short_name' => 'Clunt',
            'coordinate' => '543714.00N 0063202.00W',
            'airfields' => ['EGAA'],
        ],
        [
            'name' => 'COBBINSHAW RESERVOIR',
            'short_name' => 'Cobbin',
            'coordinate' => '554828.00N 0033400.00W',
            'airfields' => ['EGPH'],
        ],
        ['name' => 'COLERAINE', 'short_name' => 'Coler', 'coordinate' => '550754N 0064018W', 'airfields' => ['EGAE'],],
        [
            'name' => 'COLTISHALL DISUSED',
            'short_name' => 'Colti',
            'coordinate' => '524511N 0012119E',
            'airfields' => ['EGSH'],
        ],
        [
            'name' => 'COMBER',
            'short_name' => 'Comb',
            'coordinate' => '543303.00N 0054445.00W',
            'airfields' => ['EGAC'],
        ],
        [
            'name' => 'CONGLETON',
            'short_name' => 'Cong',
            'coordinate' => '530954.00N 0021051.00W',
            'airfields' => ['EGCC'],
        ],
        [
            'name' => 'CORBIERE LIGHTHOUSE',
            'short_name' => 'Corbi',
            'coordinate' => '491047.00N 0021500.00W',
            'airfields' => ['EGJJ', 'EGJB'],
        ],
        [
            'name' => 'COWES',
            'short_name' => 'Cowes',
            'coordinate' => '504541.27N 0011735.13W',
            'airfields' => ['EGHI'],
        ],
        ['name' => 'CREDITON', 'short_name' => 'Credi', 'coordinate' => '504726N 0033905W', 'airfields' => ['EGTE'],],
        ['name' => 'CULLOMPTON', 'short_name' => 'Cullo', 'coordinate' => '505128N 0032338W', 'airfields' => ['EGTE'],],
        [
            'name' => 'CULZEAN BAY/CASTLE',
            'short_name' => 'Culze',
            'coordinate' => '552210N 0044605W',
            'airfields' => ['EGPK'],
        ],
        ['name' => 'CUMNOCK', 'short_name' => 'Cumno', 'coordinate' => '552720N 0041527W', 'airfields' => ['EGPK'],],
        [
            'name' => 'DALKEITH',
            'short_name' => 'Dalk',
            'coordinate' => '555336.00N 0030406.00W',
            'airfields' => ['EGPH'],
        ],
        [
            'name' => 'DALMELLINGTON',
            'short_name' => 'Dalme',
            'coordinate' => '551924N 0042350W',
            'airfields' => ['EGPK'],
        ],
        ['name' => 'DALRYMPLE', 'short_name' => 'Dalry', 'coordinate' => '552350N 0043533W', 'airfields' => ['EGPK'],],
        [
            'name' => 'DANESHILL LAKES',
            'short_name' => 'Danes',
            'coordinate' => '532137N 0005607W',
            'airfields' => ['EGCN', 'EGNE'],
        ],
        [
            'name' => 'DEBDEN DISUSED',
            'short_name' => 'Debd',
            'coordinate' => '515931.05N 0001629.38E',
            'airfields' => ['EGSS'],
        ],
        [
            'name' => 'DERWENT RESERVOIR',
            'short_name' => 'Der Re.',
            'coordinate' => '545200N 0015848W',
            'airfields' => ['EGNT'],
        ],
        [
            'name' => 'DEWSBURY (DBY)',
            'short_name' => 'Dews',
            'coordinate' => '534130.00N 0013806.00W',
            'airfields' => ['EGNM'],
        ],
        [
            'name' => 'DIAMOND HANGAR (HANGAR 8)',
            'short_name' => 'Diam',
            'coordinate' => '515240N 0001409E',
            'airfields' => ['EGSS'],
        ],
        ['name' => 'DINGWALL', 'short_name' => 'Ding', 'coordinate' => '573558N 0042553W', 'airfields' => ['EGPE'],],
        ['name' => 'DIVIS', 'short_name' => 'Div', 'coordinate' => '543627.00N 0060034.00W', 'airfields' => ['EGAA'],],
        ['name' => 'DOONFOOT', 'short_name' => 'Doon', 'coordinate' => '552625N 0043903W', 'airfields' => ['EGPK'],],
        ['name' => 'DORES', 'short_name' => 'Dores', 'coordinate' => '572255N 0041955W', 'airfields' => ['EGPE'],],
        [
            'name' => 'DORKING',
            'short_name' => 'Dork',
            'coordinate' => '511337.00N 0002006.00W',
            'airfields' => ['EGKK'],
        ],
        [
            'name' => 'DOVESTONES RESERVOIRS',
            'short_name' => 'Doves',
            'coordinate' => '533215N 0015812W',
            'airfields' => ['EGCC'],
        ],
        [
            'name' => 'DRAYCOTE WATER',
            'short_name' => 'Dray',
            'coordinate' => '521934N 0011935W',
            'airfields' => ['EGBE'],
        ],
        [
            'name' => 'DUMBARTON',
            'short_name' => 'Dumb',
            'coordinate' => '555640.00N 0043406.00W',
            'airfields' => ['EGPF'],
        ],
        [
            'name' => 'DUNCANSBY HEAD LIGHTHOUSE',
            'short_name' => 'Dunc',
            'coordinate' => '583838N 0030131W',
            'airfields' => ['EGPC'],
        ],
        ['name' => 'DUNGIVEN', 'short_name' => 'Dungi', 'coordinate' => '545542N 0065530W', 'airfields' => ['EGAE'],],
        [
            'name' => 'DURHAM',
            'short_name' => 'Durh',
            'coordinate' => '544626.00N 0013436.00W',
            'airfields' => ['EGNT'],
        ],
        [
            'name' => 'EAST KILBRIDE',
            'short_name' => 'E Kil',
            'coordinate' => '554550.00N 0041020.00W',
            'airfields' => ['EGPF'],
        ],
        [
            'name' => 'EAST NAILSEA',
            'short_name' => 'E Nail',
            'coordinate' => '512548.00N 0024406.00W',
            'airfields' => ['EGGD'],
        ],
        [
            'name' => 'ECCUP RESERVOIR (ECP)',
            'short_name' => 'Eccup',
            'coordinate' => '535216.00N 0013236.00W',
            'airfields' => ['EGNM'],
        ],
        [
            'name' => 'ELSHAM WOLDS',
            'short_name' => 'Elsh',
            'coordinate' => '533631N 0002541W',
            'airfields' => ['EGNJ'],
        ],
        ['name' => 'EPPING', 'short_name' => 'Epp', 'coordinate' => '514200.00N 0000640.00E', 'airfields' => ['EGSS'],],
        [
            'name' => 'ERSKINE BRIDGE',
            'short_name' => 'Erski',
            'coordinate' => '555513.00N 0042746.00W',
            'airfields' => ['EGPF'],
        ],
        ['name' => 'EXMOUTH', 'short_name' => 'Exmo', 'coordinate' => '503729N 0032408W', 'airfields' => ['EGTE'],],
        [
            'name' => 'FARINGDON',
            'short_name' => 'Faring',
            'coordinate' => '513918.00N 0013512.00W',
            'airfields' => ['EGVN'],
        ],
        [
            'name' => 'FARMOOR RESERVOIR',
            'short_name' => 'Far R.',
            'coordinate' => '514512.00N 0012124.00W',
            'airfields' => ['EGVN'],
        ],
        [
            'name' => 'FARNHAM CASTLE',
            'short_name' => 'Farn',
            'coordinate' => '511307N 0004808W',
            'airfields' => ['EGLF'],
        ],
        [
            'name' => 'FIDDLERS FERRY POWER STATION',
            'short_name' => 'Fiddle',
            'coordinate' => '532218.39N 0024116.03W',
            'airfields' => ['EGGP'],
        ],
        [
            'name' => 'FLAT HOLM LIGHTHOUSE',
            'short_name' => 'Flat H',
            'coordinate' => '512232.00N 0030707.00W',
            'airfields' => ['EGFF', 'EGSY'],
        ],
        ['name' => 'FLEET POND', 'short_name' => 'Fleet', 'coordinate' => '511719N 0004929W', 'airfields' => ['EGLF'],],
        [
            'name' => 'FLEETWOOD (GOLF COURSE)',
            'short_name' => 'Fleet',
            'coordinate' => '535508N 0030243W',
            'airfields' => ['EGNH'],
        ],
        [
            'name' => 'FLINT BRIDGE',
            'short_name' => 'Flint',
            'coordinate' => '531346N 0030400W',
            'airfields' => ['EGNR'],
        ],
        ['name' => 'FOOT', 'short_name' => 'Foot', 'coordinate' => '590143N 0024823W', 'airfields' => ['EGPA'],],
        [
            'name' => 'FORT LE MARCHANT',
            'short_name' => 'Fort',
            'coordinate' => '493032.00N 0023107.00W',
            'airfields' => ['EGJJ', 'EGJB'],
        ],
        [
            'name' => 'FORTH ROAD BRIDGE (NORTH TOWER)',
            'short_name' => 'Forth',
            'coordinate' => '560022N 0032414W',
            'airfields' => ['EGPH'],
        ],
        [
            'name' => 'FRANKLEY RESERVOIRS',
            'short_name' => 'Frank',
            'coordinate' => '522513.00N 0015955.00W',
            'airfields' => ['EGBB'],
        ],
        [
            'name' => 'FREMONT TV MAST',
            'short_name' => 'Frem',
            'coordinate' => '491506N 0020753W',
            'airfields' => ['EGJJ', 'EGJB'],
        ],
        [
            'name' => 'FRENSHAM GREAT POND',
            'short_name' => 'Fren',
            'coordinate' => '510916N 0004730W',
            'airfields' => ['EGLF'],
        ],
        [
            'name' => 'FRODSHAM HILL',
            'short_name' => 'Frod',
            'coordinate' => '531713.75N 0024329.27W',
            'airfields' => ['EGGP'],
        ],
        ['name' => 'FUGLA', 'short_name' => 'Fugla', 'coordinate' => '602657N 0011926W', 'airfields' => ['EGPM'],],
        [
            'name' => 'GAINSBOROUGH',
            'short_name' => 'Gains',
            'coordinate' => '532334N 0004615W',
            'airfields' => ['EGCN', 'EGNE'],
        ],
        [
            'name' => 'GARSTANG MARINA',
            'short_name' => 'Garst',
            'coordinate' => '535419.50N 0024730.20W',
            'airfields' => ['EGNO'],
        ],
        [
            'name' => 'GARSTON DOCKS',
            'short_name' => 'Garst',
            'coordinate' => '532109.96N 0025424.36W',
            'airfields' => ['EGGP'],
        ],
        [
            'name' => 'GATEWAY PORT',
            'short_name' => 'Gate',
            'coordinate' => '513017N 0003011E',
            'airfields' => ['EGMC'],
        ],
        [
            'name' => 'GLENGORMLEY M2/J4',
            'short_name' => 'Gleng',
            'coordinate' => '544050N 0055854W',
            'airfields' => ['EGAA'],
        ],
        ['name' => 'GLOSSOP', 'short_name' => 'Gloss', 'coordinate' => '532626N 0015504W', 'airfields' => ['EGCC'],],
        [
            'name' => 'GODSTONE (A25/B2236 JUNCTION)',
            'short_name' => 'Gods J.',
            'coordinate' => '511450N 0000401W',
            'airfields' => ['EGKR'],
        ],
        [
            'name' => 'GODSTONE RAILWAY STATION',
            'short_name' => 'Gods R.',
            'coordinate' => '511305N 0000304W',
            'airfields' => ['EGKR'],
        ],
        ['name' => 'GOLF COURSE', 'short_name' => 'Golf', 'coordinate' => '514000N 0001256W', 'airfields' => ['EGTR'],],
        [
            'name' => 'GOOLE DOCKS',
            'short_name' => 'G. Dock',
            'coordinate' => '534149N 0005240W',
            'airfields' => ['EGCN'],
        ],
        [
            'name' => 'GREENOCK',
            'short_name' => 'Green',
            'coordinate' => '555650.00N 0044505.00W',
            'airfields' => ['EGPF'],
        ],
        ['name' => 'GRETNA', 'short_name' => 'Gret', 'coordinate' => '545944N 0030403W', 'airfields' => ['EGNC'],],
        [
            'name' => 'GRIMS TOWER',
            'short_name' => 'Grims',
            'coordinate' => '513722.45N 0002123.57W',
            'airfields' => ['EGLL'],
        ],
        [
            'name' => 'GROOMSPORT',
            'short_name' => 'Groom',
            'coordinate' => '544030.00N 0053705.00W',
            'airfields' => ['EGAC'],
        ],
        [
            'name' => 'GUILDFORD',
            'short_name' => 'Guild',
            'coordinate' => '511422.00N 0003506.00W',
            'airfields' => ['EGKK', 'EGLF'],
        ],
        ['name' => 'HALTWHISTLE', 'short_name' => 'Halt', 'coordinate' => '545808N 0022744W', 'airfields' => ['EGNC'],],
        [
            'name' => 'HANDCROSS',
            'short_name' => 'Hand',
            'coordinate' => '510310.00N 0001208.00W',
            'airfields' => ['EGKK'],
        ],
        [
            'name' => 'HANOIS LIGHTHOUSE',
            'short_name' => 'Hanois',
            'coordinate' => '492606.00N 0024209.00W',
            'airfields' => ['EGJJ', 'EGJB'],
        ],
        [
            'name' => 'HARROGATE (HGT)',
            'short_name' => 'Harro',
            'coordinate' => '535930.00N 0013136.00W',
            'airfields' => ['EGNM'],
        ],
        [
            'name' => 'HARTLEPOOL',
            'short_name' => 'Hartl',
            'coordinate' => '544100.00N 0011250.00W',
            'airfields' => ['EGNV'],
        ],
        [
            'name' => 'HAVERHILL',
            'short_name' => 'Haver',
            'coordinate' => '520457.00N 0002604.00E',
            'airfields' => ['EGSS'],
        ],
        ['name' => 'HAXEY', 'short_name' => 'Haxey', 'coordinate' => '532925N 0005037W', 'airfields' => ['EGCN'],],
        [
            'name' => 'HAYDOCK PARK RACECOURSE',
            'short_name' => 'Hay Race',
            'coordinate' => '532842N 0023720W',
            'airfields' => ['airfields' => 'EGGP', 'EGCB', 'EGCC',],
        ],
        [
            'name' => 'HAYWARDS HEATH',
            'short_name' => 'Hay He',
            'coordinate' => '510027.00N 0000546.00W',
            'airfields' => ['EGKK'],
        ],
        [
            'name' => 'HAZELEND WOOD',
            'short_name' => 'Hazel',
            'coordinate' => '515338.88N 0001015.05E',
            'airfields' => ['EGSS'],
        ],
        [
            'name' => 'HEADS OF AYR',
            'short_name' => 'Heads',
            'coordinate' => '552558N 0044247W',
            'airfields' => ['EGPK'],
        ],
        [
            'name' => 'HEAUVILLE',
            'short_name' => 'Heauv',
            'coordinate' => '493459.00N 0014807.00W',
            'airfields' => ['EGJJ', 'EGJB'],
        ],
        [
            'name' => 'HELSBY HILL',
            'short_name' => 'Hels',
            'coordinate' => '531624.31N 0024547.64W',
            'airfields' => ['EGGP'],
        ],
        [
            'name' => 'HENGISTBURY HEAD',
            'short_name' => 'Hengi',
            'coordinate' => '504243.00N 0014456.00W',
            'airfields' => ['EGHH'],
        ],
        [
            'name' => 'HERM ISLAND',
            'short_name' => 'Herm',
            'coordinate' => '492818.07N 0022655.46W',
            'airfields' => ['EGJJ', 'EGJB'],
        ],
        [
            'name' => 'HERMISTON (M8 Junction 1)',
            'short_name' => 'Herm',
            'coordinate' => '555530N 0031843W',
            'airfields' => ['EGPH'],
        ],
        [
            'name' => 'HETHEL DISUSED',
            'short_name' => 'Heth',
            'coordinate' => '523345N 0011030E',
            'airfields' => ['EGSH'],
        ],
        ['name' => 'HEXHAM', 'short_name' => 'Hex', 'coordinate' => '545815.00N 0020610.00W', 'airfields' => ['EGNT'],],
        [
            'name' => 'HILLEND SKI SLOPE',
            'short_name' => 'Hill',
            'coordinate' => '555318.00N 0031230.00W',
            'airfields' => ['EGPH'],
        ],
        ['name' => 'HILLSWICK', 'short_name' => 'Hill', 'coordinate' => '602833N 0012919W', 'airfields' => ['EGPM'],],
        [
            'name' => 'HILLTOP',
            'short_name' => 'Hill',
            'coordinate' => '532030.00N 0021027.00W',
            'airfields' => ['EGCC'],
        ],
        ['name' => 'HOOK', 'short_name' => 'Hook', 'coordinate' => '511646N 0005743W', 'airfields' => ['EGLF'],],
        [
            'name' => 'HULTON INDUSTRIAL ESTATE',
            'short_name' => 'Hulton',
            'coordinate' => '533206.28N 0022704.56W',
            'airfields' => ['EGCB'],
        ],
        [
            'name' => 'HURST CASTLE',
            'short_name' => 'Hurst',
            'coordinate' => '504229N 0013301W',
            'airfields' => ['EGHH'],
        ],
        ['name' => 'HYDE', 'short_name' => 'Hyde', 'coordinate' => '515039.00N 0002158.00W', 'airfields' => ['EGGW'],],
        [
            'name' => 'IMMINGHAM DOCKS',
            'short_name' => 'Immi',
            'coordinate' => '533742N 0001136W',
            'airfields' => ['EGNJ'],
        ],
        [
            'name' => 'INSCH',
            'short_name' => 'Insch',
            'coordinate' => '572034.00N 0023651.00W',
            'airfields' => ['EGPD'],
        ],
        [
            'name' => 'INSKIP (DISUSED AD)',
            'short_name' => 'Insk',
            'coordinate' => '534938N 0025003W',
            'airfields' => ['EGNH'],
        ],
        [
            'name' => 'INVERGORDON',
            'short_name' => 'Inver',
            'coordinate' => '574132N 0041003W',
            'airfields' => ['EGPE'],
        ],
        [
            'name' => 'INVERKIP POWER STATION',
            'short_name' => 'Inver',
            'coordinate' => '555354.00N 0045312.00W',
            'airfields' => ['EGPF'],
        ],
        [
            'name' => 'IRLAM',
            'short_name' => 'Irlam',
            'coordinate' => '532620N 0022447W',
            'airfields' => ['EGCC', 'EGCB'],
        ],
        [
            'name' => 'IRVINE HARBOUR',
            'short_name' => 'Irvin',
            'coordinate' => '553639N 0044155W',
            'airfields' => ['EGPK'],
        ],
        [
            'name' => 'JAGUAR CAR FACTORY',
            'short_name' => 'Jaguar',
            'coordinate' => '532112.66N 0025008.80W',
            'airfields' => ['EGGP'],
        ],
        [
            'name' => 'JODRELL BANK',
            'short_name' => 'Jodre',
            'coordinate' => '531411.00N 0021833.00W',
            'airfields' => ['EGCC'],
        ],
        [
            'name' => 'KEIGHLEY (KLY)',
            'short_name' => 'Keigh',
            'coordinate' => '535200.00N 0015436.00W',
            'airfields' => ['EGNM'],
        ],
        [
            'name' => 'KEISS VILLAGE',
            'short_name' => 'Keiss',
            'coordinate' => '583200N 0030724W',
            'airfields' => ['EGPC'],
        ],
        [
            'name' => 'KELTY',
            'short_name' => 'Kelty',
            'coordinate' => '560805.00N 0032315.00W',
            'airfields' => ['EGPH'],
        ],
        [
            'name' => 'KESWICK ROUNDABOUT',
            'short_name' => 'Keswi',
            'coordinate' => '523517N 0011630E',
            'airfields' => ['EGSH'],
        ],
        [
            'name' => 'KIDBROOKE FLATS',
            'short_name' => 'Kidbro',
            'coordinate' => '512741.29N 0000136.68E',
            'airfields' => ['EGLC'],
        ],
        [
            'name' => 'KILMACOLM',
            'short_name' => 'Kilmac',
            'coordinate' => '555340.00N 0043739.00W',
            'airfields' => ['EGPF'],
        ],
        [
            'name' => 'KILMARNOCK',
            'short_name' => 'Kilmar',
            'coordinate' => '553645.00N 0042954.00W',
            'airfields' => ['EGPF', 'EGPK'],
        ],
        [
            'name' => 'KIMPTON HALL',
            'short_name' => 'Kimp',
            'coordinate' => '515045.00N 0001748.00W',
            'airfields' => ['EGGW'],
        ],
        [
            'name' => 'KINGSTON BRIDGE',
            'short_name' => 'Kings',
            'coordinate' => '555122.00N 0041611.00W',
            'airfields' => ['EGPF'],
        ],
        [
            'name' => 'KIRKBY',
            'short_name' => 'Kirk',
            'coordinate' => '532848.00N 0025254.00W',
            'airfields' => ['EGGP'],
        ],
        [
            'name' => 'KIRKCALDY HARBOUR',
            'short_name' => 'Kirk',
            'coordinate' => '560650.00N 0030900.00W',
            'airfields' => ['EGPH'],
        ],
        [
            'name' => 'KIRKLISTON',
            'short_name' => 'Kirkl',
            'coordinate' => '555720.00N 0032411.00W',
            'airfields' => ['EGPH'],
        ],
        [
            'name' => 'KIRKNEWTON',
            'short_name' => 'Kirkn',
            'coordinate' => '555315.00N 0032505.00W',
            'airfields' => ['EGPH'],
        ],
        [
            'name' => 'LACEBY CROSSROADS',
            'short_name' => 'Lace',
            'coordinate' => '533207N 0001049W',
            'airfields' => ['EGNJ'],
        ],
        [
            'name' => 'LAMALOAD RESERVOIR',
            'short_name' => 'Lamal',
            'coordinate' => '531620N 0020233W',
            'airfields' => ['EGCC'],
        ],
        [
            'name' => 'LAMB HOLM ISLAND',
            'short_name' => 'Lamb',
            'coordinate' => '585314N 0025336W',
            'airfields' => ['EGPA'],
        ],
        ['name' => 'LANGHOLM', 'short_name' => 'Lang', 'coordinate' => '550911N 0030000W', 'airfields' => ['EGNC'],],
        [
            'name' => 'LARNE',
            'short_name' => 'Larne',
            'coordinate' => '545112.00N 0054931.00W',
            'airfields' => ['EGAA'],
        ],
        [
            'name' => 'LAVERNOCK POINT',
            'short_name' => 'Laver',
            'coordinate' => '512423.00N 0031014.00W',
            'airfields' => ['EGFF', 'EGSY'],
        ],
        [
            'name' => 'LAXEY',
            'short_name' => 'Laxey',
            'coordinate' => '541345.00N 0042406.00W',
            'airfields' => ['EGNS'],
        ],
        [
            'name' => 'LECHLADE',
            'short_name' => 'Lechl',
            'coordinate' => '514136.00N 0014124.00W',
            'airfields' => ['EGVN'],
        ],
        [
            'name' => 'LEIGH FLASH',
            'short_name' => 'Leigh',
            'coordinate' => '532923N 0023335W',
            'airfields' => ['EGCC', 'EGCB'],
        ],
        [
            'name' => 'LENWADE LAKES',
            'short_name' => 'Lenwa',
            'coordinate' => '524307N 0010609E',
            'airfields' => ['EGSH'],
        ],
        [
            'name' => 'LETTERKENNY OFFICE PARK',
            'short_name' => 'Letter',
            'coordinate' => '545754N 0074351W',
            'airfields' => ['EGAE'],
        ],
        [
            'name' => 'LEWES INTERSECTION (A27(T)/A26)',
            'short_name' => 'Lewis',
            'coordinate' => '505152N 0000127E',
            'airfields' => ['EGKA'],
        ],
        [
            'name' => 'LICHFIELD CITY RAILWAY JUNCTION',
            'short_name' => 'Lich',
            'coordinate' => '524110.00N 0014755.00W',
            'airfields' => ['EGBB'],
        ],
        [
            'name' => 'LIFFORD BRIDGE',
            'short_name' => 'Liff Br',
            'coordinate' => '544953N 0072847W',
            'airfields' => ['EGAE'],
        ],
        [
            'name' => 'LINGA ISLAND',
            'short_name' => 'Linga',
            'coordinate' => '602124N 0012134W',
            'airfields' => ['EGPM'],
        ],
        [
            'name' => 'LITTLEHAMPTON',
            'short_name' => 'Little',
            'coordinate' => '504846N 0003247W',
            'airfields' => ['EGKA'],
        ],
        [
            'name' => 'LLANDEGFEDD RESERVOIR',
            'short_name' => 'Lland R',
            'coordinate' => '514129.72N 0025814.51W',
            'airfields' => ['EGFF', 'EGSY'],
        ],
        ['name' => 'LOCH WATTEN', 'short_name' => 'Lock', 'coordinate' => '582900N 0032006W', 'airfields' => ['EGPC'],],
        ['name' => 'LOCHINDORB', 'short_name' => 'Loch', 'coordinate' => '572410N 0034257W', 'airfields' => ['EGPE'],],
        [
            'name' => 'LOCHMADDY PIER',
            'short_name' => 'Loch',
            'coordinate' => '573546N 0070924W',
            'airfields' => ['EGPL'],
        ],
        ['name' => 'LOCKERBIE', 'short_name' => 'Lock', 'coordinate' => '550714N 0032124W', 'airfields' => ['EGNC'],],
        [
            'name' => 'LONDON EYE',
            'short_name' => 'Eye',
            'coordinate' => '513012.52N 0000711.45W',
            'airfields' => ['EGLC', 'EGLL'],
        ],
        [
            'name' => 'LONGANNET POWER STATION',
            'short_name' => 'Longa',
            'coordinate' => '560256N 0034057W',
            'airfields' => ['EGPH'],
        ],
        ['name' => 'LUNNA HOLM', 'short_name' => 'Lunna', 'coordinate' => '602715N 0010234W', 'airfields' => ['EGPM'],],
        [
            'name' => 'LYBSTER VILLAGE',
            'short_name' => 'Lybst',
            'coordinate' => '581800N 0031706W',
            'airfields' => ['EGPC'],
        ],
        [
            'name' => 'M1 JUNCTION 22 MARKFIELD',
            'short_name' => 'M1 J22',
            'coordinate' => '524144N 0011733W',
            'airfields' => ['EGNX'],
        ],
        [
            'name' => 'M1 JUNCTION 8',
            'short_name' => 'M1 J8',
            'coordinate' => '514522N 0002458W',
            'airfields' => ['EGGW'],
        ],
        [
            'name' => 'M1/A1(M) JUNCTION',
            'short_name' => 'M1/A1 J',
            'coordinate' => '534851.75N 0012025.27W',
            'airfields' => ['EGCM'],
        ],
        [
            'name' => 'M1/M18 THURCROFT INTERCHANGE',
            'short_name' => 'M1 Thur',
            'coordinate' => '532334N 0011643W',
            'airfields' => ['EGCN'],
        ],
        [
            'name' => 'M11 Junction 4',
            'short_name' => 'M11 J4',
            'coordinate' => '513538N 0000213E',
            'airfields' => ['EGLC'],
        ],
        [
            'name' => 'M18 STAINFORTH SERVICES',
            'short_name' => 'Stain',
            'coordinate' => '533529N 0005915W',
            'airfields' => ['EGCN'],
        ],
        [
            'name' => 'M25 Junction 13',
            'short_name' => 'M25 J13',
            'coordinate' => '512639.89N 0003145.82W',
            'airfields' => ['EGLL'],
        ],
        [
            'name' => 'M25 JUNCTION 7/M23 JUNCTION 8',
            'short_name' => 'M25/M23',
            'coordinate' => '511550N 0000741W',
            'airfields' => ['EGKR'],
        ],
        [
            'name' => 'M3 JUNCTION 3',
            'short_name' => 'M3 J3',
            'coordinate' => '512121.06N 0004050.40W',
            'airfields' => ['EGLF', 'EGLL'],
        ],
        [
            'name' => 'M3 JUNCTION 4',
            'short_name' => 'M3 J4',
            'coordinate' => '511859N 0004525W',
            'airfields' => ['EGLF'],
        ],
        [
            'name' => 'M4 JUNCTION 18',
            'short_name' => 'M4 J18',
            'coordinate' => '513007N 0022100W',
            'airfields' => ['EGGD'],
        ],
        [
            'name' => 'M4 JUNCTION 24',
            'short_name' => 'M4 J24',
            'coordinate' => '513607N 0025532W',
            'airfields' => ['EGFF', 'EGSY'],
        ],
        [
            'name' => 'M4 JUNCTION 36 (SERVICES) (NORTH OF BRIDGEND)',
            'short_name' => 'M4 J36',
            'coordinate' => '513156N 0033424W',
            'airfields' => ['EGFF', 'EGSY'],
        ],
        [
            'name' => 'M40 JUNCTION 2',
            'short_name' => 'M40 J2',
            'coordinate' => '513539.70N 0003739.12W',
            'airfields' => ['EGLL'],
        ],
        [
            'name' => 'M40/M42 INTERCHANGE',
            'short_name' => 'M40/M42',
            'coordinate' => '522055.00N 0014835.00W',
            'airfields' => ['EGBB'],
        ],
        [
            'name' => 'M42 JUNCTION 10 (TAMWORTH)',
            'short_name' => 'M42 J10',
            'coordinate' => '523612.00N 0013833.00W',
            'airfields' => ['EGBB'],
        ],
        [
            'name' => 'M42 JUNCTION 11 MEASHAM',
            'short_name' => 'M42 J11',
            'coordinate' => '524120.00N 0013253.00W',
            'airfields' => ['EGNX'],
        ],
        [
            'name' => 'M5 AVON BRIDGE',
            'short_name' => 'M5 Av',
            'coordinate' => '512920.06N 0024134.59W',
            'airfields' => ['EGGD']
        ],
        [
            'name' => 'M5 SEDGEMOOR SERVICES',
            'short_name' => 'M5 Sed',
            'coordinate' => '511608.11N 0025516.58W',
            'airfields' => ['EGGD'],
        ],
        [
            'name' => 'M53N Junction 10 (CHESHIRE OAKS)',
            'short_name' => 'M53 J10',
            'coordinate' => '531545.39N 0025234.37W',
            'airfields' => ['EGGP'],
        ],
        [
            'name' => 'M55 JUNCTION 3',
            'short_name' => 'M55 J3',
            'coordinate' => '534825.00N 0025323.00W',
            'airfields' => ['EGNH', 'EGNO']
        ],
        [
            'name' => 'M55 JUNCTION 4',
            'short_name' => 'M55 J4',
            'coordinate' => '534737.98N 0025905.26W',
            'airfields' => ['EGNH'],
        ],
        [
            'name' => 'M56 JUNCTION 10',
            'short_name' => 'M56 J10',
            'coordinate' => '532004N 0023417W',
            'airfields' => ['EGCC'],
        ],
        [
            'name' => 'M56 JUNCTION 11',
            'short_name' => 'M56 J11',
            'coordinate' => '531938N 0023837W',
            'airfields' => ['EGGP', 'EGCC'],
        ],
        [
            'name' => 'M6 HILTON PARK SERVICES',
            'short_name' => 'M6 Hil',
            'coordinate' => '523838.00N 0020323.00W',
            'airfields' => ['EGBB'],
        ],
        [
            'name' => 'M6 JUNCTION 3 (BEDWORTH)',
            'short_name' => 'M6 J3',
            'coordinate' => '522745.00N 0012939.00W',
            'airfields' => ['EGBB'],
        ],
        [
            'name' => 'M6 JUNCTION 30/ M61',
            'short_name' => 'M6 J30',
            'coordinate' => '534408.10N 0023856.10W',
            'airfields' => ['EGNO'],
        ],
        [
            'name' => 'M6 JUNCTION 32/M55',
            'short_name' => 'M6 J32',
            'coordinate' => '534827.40N 0024158.80W',
            'airfields' => ['EGNO'],
        ],
        [
            'name' => 'M6 SANDBACH SERVICES',
            'short_name' => 'M6 Sand',
            'coordinate' => '530822.00N 0022011.00W',
            'airfields' => ['EGCC'],
        ],
        [
            'name' => 'M60/M62/M66 HEATON INTERCHANGE',
            'short_name' => 'M60 He',
            'coordinate' => '533300N 0021540W',
            'airfields' => ['EGCC', 'EGCB'],
        ],
        [
            'name' => 'MACCLESFIELD SOUTH',
            'short_name' => 'Maccl',
            'coordinate' => '531410N 0020805W',
            'airfields' => ['EGCC'],
        ],
        [
            'name' => 'MAPLE CROSS',
            'short_name' => 'Maple',
            'coordinate' => '513746.00N 0003015.00W',
            'airfields' => ['EGLD'],
        ],
        ['name' => 'MAUCHLINE', 'short_name' => 'Mauch', 'coordinate' => '553057N 0042245W', 'airfields' => ['EGPK'],],
        [
            'name' => 'MELDRUM TV MAST',
            'short_name' => 'Meld',
            'coordinate' => '572309.20N 0022403.10W',
            'airfields' => ['EGPD'],
        ],
        [
            'name' => 'MELTON MOWBRAY DISUSED',
            'short_name' => 'Melt',
            'coordinate' => '524422.00N 0005334.00W',
            'airfields' => ['EGNX'],
        ],
        [
            'name' => 'MIDDLEBROOK STADIUM',
            'short_name' => 'Middl',
            'coordinate' => '533450N 0023208W',
            'airfields' => ['EGCC', 'EGCB'],
        ],
        [
            'name' => 'MINEHEAD',
            'short_name' => 'Mineh',
            'coordinate' => '511221.00N 0032830.00W',
            'airfields' => ['EGFF', 'EGSY'],
        ],
        [
            'name' => 'MINQUIES',
            'short_name' => 'Minq',
            'coordinate' => '485800N 0020800W',
            'airfields' => ['EGJJ', 'EGJB'],
        ],
        [
            'name' => 'MOLD TOWN A494/A541 Chester Road roundabout (East of Mold Town).',
            'short_name' => 'Mold',
            'coordinate' => '530954N 0030731W',
            'airfields' => ['EGNR'],
        ],
        [
            'name' => 'MONACH ISLANDS LIGHTHOUSE',
            'short_name' => 'M Light',
            'coordinate' => '573135N 0074139W',
            'airfields' => ['EGPL'],
        ],
        [
            'name' => 'MORPETH RAILWAY STATION',
            'short_name' => 'Morp',
            'coordinate' => '550945N 0014058W',
            'airfields' => ['EGNT'],
        ],
        [
            'name' => 'MOTORWAY JUNCTION A1(M)/A66(M)',
            'short_name' => 'A1M/A66M',
            'coordinate' => '543000N 0013736W',
            'airfields' => ['EGNV'],
        ],
        [
            'name' => 'MOUSA',
            'short_name' => 'Mousa',
            'coordinate' => '600000.00N 0010936.00W',
            'airfields' => ['EGPB'],
        ],
        ['name' => 'MOVILLE', 'short_name' => 'Movil', 'coordinate' => '551124N 0070224W', 'airfields' => ['EGAE'],],
        ['name' => 'MULL OF OA', 'short_name' => 'Mull', 'coordinate' => '553530N 0062018W', 'airfields' => ['EGPI'],],
        [
            'name' => 'MUSSELBURGH RACECOURSE',
            'short_name' => 'Mussl',
            'coordinate' => '555650.00N 0030225.00W',
            'airfields' => ['EGPH'],
        ],
        [
            'name' => 'NABURN MARINA',
            'short_name' => 'Nabur',
            'coordinate' => '535433.85N 0010522.80W',
            'airfields' => ['EGCM'],
        ],
        [
            'name' => 'NASH POINT LIGHTHOUSE',
            'short_name' => 'NashP',
            'coordinate' => '512403.00N 0033308.00W',
            'airfields' => ['EGFF', 'EGSY'],
        ],
        [
            'name' => 'NASH SOUTH',
            'short_name' => 'NashS',
            'coordinate' => '512253.00N 0033327.00W',
            'airfields' => ['EGFF', 'EGSY'],
        ],
        [
            'name' => 'NEEDLES LIGHTHOUSE',
            'short_name' => 'Needl',
            'coordinate' => '503945N 0013529W',
            'airfields' => ['EGHI', 'EGHH',],
        ],
        [
            'name' => 'NESTON',
            'short_name' => 'Nest',
            'coordinate' => '531730.00N 0030336.00W',
            'airfields' => ['EGGP'],
        ],
        [
            'name' => 'NEW ALRESFORD',
            'short_name' => 'New Ar',
            'coordinate' => '510519.70N 0010859.10W',
            'airfields' => ['EGHI'],
        ],
        [
            'name' => 'NEW BUILDINGS',
            'short_name' => 'New B',
            'coordinate' => '545730N 0072130W',
            'airfields' => ['EGAE'],
        ],
        [
            'name' => 'NEWTON CUNNINGHAM',
            'short_name' => 'Newton',
            'coordinate' => '545954N 0073024W',
            'airfields' => ['EGAE'],
        ],
        [
            'name' => 'NOIRMONT POINT LIGHTHOUSE',
            'short_name' => 'Noirm',
            'coordinate' => '490955N 0021005W',
            'airfields' => ['EGJJ', 'EGJB'],
        ],
        [
            'name' => 'NORFOLK SHOWGROUND',
            'short_name' => 'Nor Sh',
            'coordinate' => '523901N 0011107E',
            'airfields' => ['EGSH'],
        ],
        [
            'name' => 'NORTH COAST',
            'short_name' => 'Nor Co',
            'coordinate' => '555600N 0060954W',
            'airfields' => ['EGPI'],
        ],
        [
            'name' => 'NORTH TOWER HUMBER BRIDGE',
            'short_name' => 'NT Humb',
            'coordinate' => '534251N 0002702W',
            'airfields' => ['EGNJ'],
        ],
        [
            'name' => 'NORTH WEST CORNER',
            'short_name' => 'NW Cor',
            'coordinate' => '491530.00N 0021450.00W',
            'airfields' => ['EGJJ', 'EGJB'],
        ],
        [
            'name' => 'NORTHALLERTON',
            'short_name' => 'NorAl',
            'coordinate' => '542020.00N 0012555.00W',
            'airfields' => ['EGNV'],
        ],
        [
            'name' => 'NORTHEY ISLAND',
            'short_name' => 'NorIs',
            'coordinate' => '514320N 0004319E',
            'airfields' => ['EGMC'],
        ],
        [
            'name' => 'NORTHLEACH ROUNDABOUT',
            'short_name' => 'NorLe',
            'coordinate' => '515015.00N 0015009.00W',
            'airfields' => ['EGVN'],
        ],
        [
            'name' => 'NUNEATON DISUSED AD',
            'short_name' => 'Nunea',
            'coordinate' => '523354N 0012653W',
            'airfields' => ['EGBE'],
        ],
        [
            'name' => 'NUTHAMPSTEAD AD',
            'short_name' => 'Nutham',
            'coordinate' => '515924.00N 0000343.00E',
            'airfields' => ['EGSS'],
        ],
        [
            'name' => 'OFFLEY',
            'short_name' => 'Offley',
            'coordinate' => '515601.00N 0002030.00W',
            'airfields' => ['EGGW'],
        ],
        [
            'name' => 'OLD SEVERN BRIDGE (M48)',
            'short_name' => 'Old Sev',
            'coordinate' => '513640.00N 0023837.00W',
            'airfields' => ['EGGD', 'EGFF', 'EGSY'],
        ],
        ['name' => 'OLNEY TOWN', 'short_name' => 'Olney', 'coordinate' => '520912N 0004206W', 'airfields' => ['EGTC'],],
        [
            'name' => 'OLYMPIC',
            'short_name' => 'Olympic',
            'coordinate' => '513218.44N 0000059.34W',
            'airfields' => ['EGLC', 'EGLL'],
        ],
        [
            'name' => 'OULTON PARK',
            'short_name' => 'Oulton',
            'coordinate' => '531034.00N 0023648.00W',
            'airfields' => ['EGGP'],
        ],
        [
            'name' => 'OUSTON (DISUSED AD)',
            'short_name' => 'Ouston',
            'coordinate' => '550130.00N 0015231.00W',
            'airfields' => ['EGNT'],
        ],
        [
            'name' => 'PADESWOOD CEMENT FACTORY',
            'short_name' => 'Padesw',
            'coordinate' => '530916N 0030342W',
            'airfields' => ['EGNR'],
        ],
        ['name' => 'PEEL', 'short_name' => 'Peel', 'coordinate' => '541320.00N 0044130.00W', 'airfields' => ['EGNS'],],
        [
            'name' => 'PENDEEN LIGHTHOUSE',
            'short_name' => 'Pende',
            'coordinate' => '500955N 0054019W',
            'airfields' => ['EGHE']
        ],
        [
            'name' => 'PENICUIK',
            'short_name' => 'Penic',
            'coordinate' => '554955.00N 0031325.00W',
            'airfields' => ['EGPH'],
        ],
        ['name' => 'PENRITH', 'short_name' => 'Penri', 'coordinate' => '543952N 0024501W', 'airfields' => ['EGNC'],],
        [
            'name' => 'PETERHEAD',
            'short_name' => 'Peter',
            'coordinate' => '573025.00N 0014636.00W',
            'airfields' => ['EGPD'],
        ],
        [
            'name' => 'PHILPSTOUN (M9 JUNCTION 2)',
            'short_name' => 'M9 J2',
            'coordinate' => '555854N 0033043W',
            'airfields' => ['EGPH'],
        ],
        [
            'name' => 'PIRTON',
            'short_name' => 'Pirt',
            'coordinate' => '515818.00N 0001954.00W',
            'airfields' => ['EGGW'],
        ],
        ['name' => 'PLADDA', 'short_name' => 'Plad', 'coordinate' => '552535N 0050704W', 'airfields' => ['EGPK'],],
        [
            'name' => 'POINT DE ROZEL',
            'short_name' => 'P De R',
            'coordinate' => '492859.00N 0015059.00W',
            'airfields' => ['EGJJ', 'EGJB'],
        ],
        [
            'name' => 'POINT OF AYR LIGHTHOUSE',
            'short_name' => 'PofA',
            'coordinate' => '532125.24N 0031919.85W',
            'airfields' => ['EGNR'],
        ],
        [
            'name' => 'POLMONT',
            'short_name' => 'Polm',
            'coordinate' => '555920.00N 0034100.00W',
            'airfields' => ['EGPH'],
        ],
        [
            'name' => 'PORT ELLEN',
            'short_name' => 'Prt El',
            'coordinate' => '553800N 0061124W',
            'airfields' => ['EGPI'],
        ],
        [
            'name' => 'PORTADOWN',
            'short_name' => 'Porta',
            'coordinate' => '542530.00N 0062651.00W',
            'airfields' => ['EGAA'],
        ],
        [
            'name' => 'POULTON (RAILWAY STATION)',
            'short_name' => 'Poul R',
            'coordinate' => '535054N 0025925W',
            'airfields' => ['EGNH'],
        ],
        [
            'name' => 'POULTON DISUSED AIRFIELD',
            'short_name' => 'Poul A',
            'coordinate' => '530756N 0025330W',
            'airfields' => ['EGNR'],
        ],
        [
            'name' => 'PUCKERIDGE A10/A120 INT',
            'short_name' => 'Pucke',
            'coordinate' => '515306.00N 0000016.00E',
            'airfields' => ['EGSS'],
        ],
        ['name' => 'QEII', 'short_name' => 'QEII', 'coordinate' => '512754.51N 0001532.85E', 'airfields' => ['EGLC'],],
        [
            'name' => 'RADSTOCK',
            'short_name' => 'Radst',
            'coordinate' => '511732.00N 0022655.00W',
            'airfields' => ['EGGD'],
        ],
        [
            'name' => 'REDCAR RACECOURSE',
            'short_name' => 'Redca',
            'coordinate' => '543626N 0010351W',
            'airfields' => ['EGNV'],
        ],
        [
            'name' => 'RHINNS POINT',
            'short_name' => 'Rhinn',
            'coordinate' => '554024N 0062906W',
            'airfields' => ['EGPI'],
        ],
        [
            'name' => 'ROCHES DOUVRES LIGHTHOUSE',
            'short_name' => 'Roch D',
            'coordinate' => '490619N 0024853W',
            'airfields' => ['EGJJ', 'EGJB'],
        ],
        [
            'name' => 'ROMSEY',
            'short_name' => 'Roms',
            'coordinate' => '505927.00N 0012945.00W',
            'airfields' => ['EGHI'],
        ],
        [
            'name' => 'ROSTHERNE',
            'short_name' => 'Rosth',
            'coordinate' => '532114.00N 0022307.00W',
            'airfields' => ['EGCC'],
        ],
        [
            'name' => 'RUNCORN BRIDGE',
            'short_name' => 'Runco',
            'coordinate' => '532046.82N 0024416.41W',
            'airfields' => ['EGGP'],
        ],
        [
            'name' => 'SAINTFIELD',
            'short_name' => 'Saint',
            'coordinate' => '542737.00N 0054958.00W',
            'airfields' => ['EGAC'],
        ],
        [
            'name' => 'SALE WATER PARK',
            'short_name' => 'Sale W',
            'coordinate' => '532600.00N 0021810.00W',
            'airfields' => ['EGCC'],
        ],
        [
            'name' => 'SANDBANKS',
            'short_name' => 'Sandb',
            'coordinate' => '504100.00N 0015650.00W',
            'airfields' => ['EGHH'],
        ],
        [
            'name' => 'SEAFORTH',
            'short_name' => 'Seafo',
            'coordinate' => '532741.00N 0030205.00W',
            'airfields' => ['EGGP'],
        ],
        [
            'name' => 'SEDGEFIELD RACECOURSE',
            'short_name' => 'Sedge',
            'coordinate' => '543845N 0012806W',
            'airfields' => ['EGNV'],
        ],
        ['name' => 'SEVENOAKS', 'short_name' => 'Seven', 'coordinate' => '511636N 0001054E', 'airfields' => ['EGKB'],],
        ['name' => 'SHEERNESS', 'short_name' => 'Sheer', 'coordinate' => '512649N 0004441E', 'airfields' => ['EGMC'],],
        ['name' => 'SILLOTH', 'short_name' => 'Sillo', 'coordinate' => '545205N 0032341W', 'airfields' => ['EGNC'],],
        [
            'name' => 'SOUTH EAST CORNER',
            'short_name' => 'SE Cor',
            'coordinate' => '491000.00N 0020200.00W',
            'airfields' => ['EGJJ', 'EGJB'],
        ],
        [
            'name' => 'SOUTH WOODHAM FERRERS',
            'short_name' => 'S Wood',
            'coordinate' => '513841N 0003606E',
            'airfields' => ['EGMC'],
        ],
        ['name' => 'SOUTHAM', 'short_name' => 'Southam', 'coordinate' => '521621N 0012304W', 'airfields' => ['EGBE'],],
        [
            'name' => 'SOUTHEND PIER',
            'short_name' => 'S Pier',
            'coordinate' => '513054N 0004319E',
            'airfields' => ['EGMC'],
        ],
        [
            'name' => 'SOUTHMINSTER',
            'short_name' => 'Southm',
            'coordinate' => '513928.00N 0004949.00E',
            'airfields' => ['EGMC'],
        ],
        [
            'name' => 'SOUTHPORT PIER',
            'short_name' => 'S Pier',
            'coordinate' => '533919.10N 0030116.40W',
            'airfields' => ['EGNO'],
        ],
        [
            'name' => 'SPINNAKER TOWER',
            'short_name' => 'Spinn',
            'coordinate' => '504744N 0010631W',
            'airfields' => ['EGHI'],
        ],
        [
            'name' => 'SPRIGGS SOLAR FARM',
            'short_name' => 'Sprig',
            'coordinate' => '515802.63N 0002208.49E',
            'airfields' => ['EGSS'],
        ],
        [
            'name' => 'ST ANNES PIER',
            'short_name' => 'St Ann',
            'coordinate' => '534456.75N 0030209.11W',
            'airfields' => ['EGNH'],
        ],
        [
            'name' => 'ST CATHERINES POINT',
            'short_name' => 'St Cat',
            'coordinate' => '503435N 0011753W',
            'airfields' => ['EGHI', 'EGHH',],
        ],
        [
            'name' => 'ST GERMAIN',
            'short_name' => 'St Ger',
            'coordinate' => '491400N 0013800W',
            'airfields' => ['EGJJ', 'EGJB'],
        ],
        ['name' => 'ST GILES', 'short_name' => 'St Gi', 'coordinate' => '513802N 0003401W', 'airfields' => ['EGLD'],],
        [
            'name' => 'ST HILARY TV MAST',
            'short_name' => 'St Hil',
            'coordinate' => '512727N 0032411W',
            'airfields' => ['EGFF', 'EGSY'],
        ],
        [
            'name' => 'ST MARTINS HEAD',
            'short_name' => 'St Mar',
            'coordinate' => '495759.44N 0061558.06W',
            'airfields' => ['EGHE'],
        ],
        [
            'name' => 'ST MARTINS POINT',
            'short_name' => 'St Mar',
            'coordinate' => '492517.97N 0023141.94W',
            'airfields' => ['EGJJ', 'EGJB'],
        ],
        [
            'name' => 'STAGSHAW MASTS',
            'short_name' => 'Stags',
            'coordinate' => '550200.00N 0020125.00W',
            'airfields' => ['EGNT'],
        ],
        [
            'name' => 'STEWARTBY BRICKWORKS',
            'short_name' => 'Stew',
            'coordinate' => '520424N 0003103W',
            'airfields' => ['EGTC'],
        ],
        [
            'name' => 'STOKE HOLY CROSS',
            'short_name' => 'Stoke',
            'coordinate' => '523430N 0011953E',
            'airfields' => ['EGSH'],
        ],
        [
            'name' => 'STOKESLEY',
            'short_name' => 'Stoke',
            'coordinate' => '542811.00N 0011141.00W',
            'airfields' => ['EGNV'],
        ],
        [
            'name' => 'STONEHAVEN',
            'short_name' => 'Stone',
            'coordinate' => '565745.00N 0021236.00W',
            'airfields' => ['EGPD'],
        ],
        [
            'name' => 'STONEY CROSS (DIS AD)',
            'short_name' => 'Stone',
            'coordinate' => '505442.00N 0013925.00W',
            'airfields' => ['EGHH'],
        ],
        ['name' => 'STRABANE', 'short_name' => 'Strab', 'coordinate' => '544925N 0072753W', 'airfields' => ['EGAE'],],
        [
            'name' => 'STRETTON AERODROME',
            'short_name' => 'Stret',
            'coordinate' => '532046.00N 0023135.00W',
            'airfields' => ['EGGP', 'EGCC'],
        ],
        ['name' => 'STROMBERRY', 'short_name' => 'Strom', 'coordinate' => '590149N 0025601W', 'airfields' => ['EGPA'],],
        [
            'name' => 'STUDLEY',
            'short_name' => 'Studl',
            'coordinate' => '521604.00N 0015353.00W',
            'airfields' => ['EGBB'],
        ],
        [
            'name' => 'SUNDERLAND HARBOUR',
            'short_name' => 'Sunder',
            'coordinate' => '545506N 0012130W',
            'airfields' => ['EGNT'],
        ],
        [
            'name' => 'SWINTON INTERCHANGE',
            'short_name' => 'Swint',
            'coordinate' => '533124.00N 0022136.00W',
            'airfields' => ['EGCC', 'EGCB'],
        ],
        [
            'name' => 'TADCASTER JUNCTION',
            'short_name' => 'Tadca',
            'coordinate' => '535325.83N 0011405.94W',
            'airfields' => ['EGCM'],
        ],
        [
            'name' => 'TAFF ELY WIND FARM',
            'short_name' => 'Taff',
            'coordinate' => '513403.06N 0032815.70W',
            'airfields' => ['EGFF', 'EGSY'],
        ],
        [
            'name' => 'TALL TOWER',
            'short_name' => 'Tall',
            'coordinate' => '534856.95N 0030318.88W',
            'airfields' => ['EGNH'],
        ],
        [
            'name' => 'TARBOCK ISLAND',
            'short_name' => 'Tarbo',
            'coordinate' => '532353.86N 0024830.41W',
            'airfields' => ['EGGP'],
        ],
        [
            'name' => 'TARRANT RUSHTON (DISUSED AERODROME)',
            'short_name' => 'Tarra',
            'coordinate' => '505100.00N 0020442.00W',
            'airfields' => ['EGHH'],
        ],
        [
            'name' => 'TARVIN ROUNDABOUT',
            'short_name' => 'Tarvi',
            'coordinate' => '531141.96N 0024637.80W',
            'airfields' => ['EGGP'],
        ],
        [
            'name' => 'THAMES BARRIER',
            'short_name' => 'T Barr',
            'coordinate' => '512950N 0000213E',
            'airfields' => ['EGLC'],
        ],
        [
            'name' => 'THE LIVER BUILDING (PIER HEAD)',
            'short_name' => 'Liver',
            'coordinate' => '532420.73N 0025945.19W',
            'airfields' => ['EGGP'],
        ],
        [
            'name' => 'THELWALL VIADUCT',
            'short_name' => 'Thel V',
            'coordinate' => '532326.00N 0023021.00W',
            'airfields' => ['EGCC', 'EGCB'],
        ],
        ['name' => 'THORPE', 'short_name' => 'Thorpe', 'coordinate' => '523737N 0012242E', 'airfields' => ['EGSH'],],
        [
            'name' => 'THORSBY LAKE',
            'short_name' => 'Thors',
            'coordinate' => '531338N 0010320W',
            'airfields' => ['EGCN', 'EGNE'],
        ],
        [
            'name' => 'THRUMSTER MASTS',
            'short_name' => 'Thurm',
            'coordinate' => '582337N 0030727W',
            'airfields' => ['EGPC'],
        ],
        ['name' => 'TOMATIN', 'short_name' => 'Tomat', 'coordinate' => '572002N 0035930W', 'airfields' => ['EGPE'],],
        [
            'name' => 'TOOME (DISUSED AD)',
            'short_name' => 'Toome',
            'coordinate' => '544528.00N 0062940.00W',
            'airfields' => ['EGAA'],
        ],
        ['name' => 'TOPSHAM', 'short_name' => 'Tops', 'coordinate' => '504123N 0032849W', 'airfields' => ['EGTE'],],
        [
            'name' => 'TROWELL (M1 SERVICE)',
            'short_name' => 'Trow',
            'coordinate' => '525742.00N 0011603.00W',
            'airfields' => ['EGNX'],
        ],
        [
            'name' => 'TUNBRIDGE WELLS',
            'short_name' => 'Tunb',
            'coordinate' => '510800.00N 0001554.00E',
            'airfields' => ['EGKK'],
        ],
        ['name' => 'TURRIFF', 'short_name' => 'Turr', 'coordinate' => '573219N 0022736W', 'airfields' => ['EGPD'],],
        [
            'name' => 'TYNE BRIDGES',
            'short_name' => 'Tyne B',
            'coordinate' => '545803.00N 0013625.00W',
            'airfields' => ['EGNT'],
        ],
        ['name' => 'VOE', 'short_name' => 'VOE', 'coordinate' => '602100N 0011558W', 'airfields' => ['EGPM'],],
        ['name' => 'WARE', 'short_name' => 'Ware', 'coordinate' => '514842.00N 0000136.00W', 'airfields' => ['EGSS'],],
        [
            'name' => 'WASHINGTON INTERSECTION (A24/A283)',
            'short_name' => 'Wash',
            'coordinate' => '505434N 0002428W',
            'airfields' => ['EGKA'],
        ],
        [
            'name' => 'WELLS MAST',
            'short_name' => 'Wells',
            'coordinate' => '511413.44N 0023731.36W',
            'airfields' => ['EGGD'],
        ],
        [
            'name' => 'WEMBLEY',
            'short_name' => 'Wemb',
            'coordinate' => '513321.85N 0001646.42W',
            'airfields' => ['EGLL'],
        ],
        [
            'name' => 'WENVOE TV MAST',
            'short_name' => 'Wenvo',
            'coordinate' => '512733.48N 0031653.65W',
            'airfields' => ['EGFF', 'EGSY'],
        ],
        [
            'name' => 'WEST KILBRIDE',
            'short_name' => 'West K',
            'coordinate' => '554108N 0045205W',
            'airfields' => ['EGPK'],
        ],
        [
            'name' => 'WEST LINTON',
            'short_name' => 'West L',
            'coordinate' => '554510.00N 0032127.00W',
            'airfields' => ['EGPH'],
        ],
        [
            'name' => 'WEST MEON CROSS ROADS',
            'short_name' => 'West M',
            'coordinate' => '510152.90N 0010430.22W',
            'airfields' => ['EGHI'],
        ],
        [
            'name' => 'WHALEY BRIDGE',
            'short_name' => 'Whal',
            'coordinate' => '531935N 0015930W',
            'airfields' => ['EGCC'],
        ],
        [
            'name' => 'WHITEHEAD',
            'short_name' => 'White',
            'coordinate' => '544510.00N 0054234.00W',
            'airfields' => ['EGAC'],
        ],
        [
            'name' => 'WHITSTABLE HARBOUR',
            'short_name' => 'Whits',
            'coordinate' => '512148N 0010136E',
            'airfields' => ['EGMC'],
        ],
        [
            'name' => 'WICKHAM',
            'short_name' => 'Wickh',
            'coordinate' => '505400.03N 0011114.80W',
            'airfields' => ['EGHI'],
        ],
        [
            'name' => 'WIGAN LAKES',
            'short_name' => 'Wig La',
            'coordinate' => '533116.81N 0023740.26W',
            'airfields' => ['EGCC', 'EGCB', 'EGGP'],
        ],
        ['name' => 'WIGTON', 'short_name' => 'Wigton', 'coordinate' => '544929N 0030940W', 'airfields' => ['EGNC'],],
        [
            'name' => 'WINSFORD FLASH',
            'short_name' => 'Wins',
            'coordinate' => '531106N 0023044W',
            'airfields' => ['EGCC'],
        ],
        [
            'name' => 'WINTER HILL MAST',
            'short_name' => 'Winter',
            'coordinate' => '533732.01N 0023053.74W',
            'airfields' => ['EGCC', 'EGCB', 'EGGP'],
        ],
        [
            'name' => 'WOBURN TOWN',
            'short_name' => 'Woburn',
            'coordinate' => '515924N 0003709W',
            'airfields' => ['EGTC'],
        ],
        ['name' => 'WORKINGTON', 'short_name' => 'Worki', 'coordinate' => '543906N 0033440W', 'airfields' => ['EGNC'],],
        [
            'name' => 'WORPLESDON STATION',
            'short_name' => 'Worple',
            'coordinate' => '511716N 0003457W',
            'airfields' => ['EGLF'],
        ],
    ];

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        foreach (self::VRPS as $vrpData) {
            $coordinateSplit = explode(' ', $vrpData['coordinate']);
            $coordinate = SectorfileService::coordinateFromNats($coordinateSplit[0], $coordinateSplit[1]);
            $vrp = VisualReferencePoint::create(
                [
                    'name' => ucwords(strtolower($vrpData['name']), ' /('),
                    'short_name' => $vrpData['short_name'],
                    'latitude' => $coordinate->getLat(),
                    'longitude' => $coordinate->getLng()
                ]
            );

            $vrp->airfields()->sync(Airfield::whereIn('code', $vrpData['airfields'])->pluck('id'));
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
